name: ai_clinic_app

description: Flutter app with Clean Architecture and BLoC

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.6

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency injection
  get_it: ^7.6.4

  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # File/image picking
  image_picker: ^1.1.1
  file_picker: ^6.1.1
  image: ^4.1.7
  universal_io: ^2.2.2

  # HTTP
  http: ^1.2.1

  # JSON serialization (optional for models)
  json_annotation: ^4.8.1

  # Flutter web/desktop utils (optional)
  flutter_svg: ^2.0.9

  # Logging (optional)
  logger: ^2.0.2+1

  # Routing (optional)
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/




  